version: '3'

services:
  api:
    container_name: model_api
    image: leommontesanti/kaggle_creditcardfraud_model_api:latest
    networks:
      - local_net
    ports:
      -"5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  bathc_process:
    image: leommontesanti/kaggle_creditcardfraud_batch:latest
    links:
      - db
    ports:
      - "5001:5001"